import { Metadata } from 'next';
import { Press_Start_2P } from 'next/font/google';
import 'nes.css/css/nes.min.css';

import './globals.css';
import { Header } from '@/components/header';

const pressStart2P = Press_Start_2P({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Meu portfolio - Samuel Medeiros',
  description: 'Generated by samuelfsd'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <link rel="icon" href="favicon.ico" sizes="any" />
      <body className={pressStart2P.className}>
        <div className="flex flex-col min-h-screen">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
