iport {} from "next/font"
import "./globals.css";

const = pressTo

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by samuelfsd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
